format_version: v1.0
type: UniqueComponent
attributes: {id: AmazonFreeRTOS}
children:
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: AmazonHWInterface}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: AmazonHWInterface}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: AmazonHWInterface}
- type: ElementPosition
  attributes: {x: '392', y: '494', id: AmazonFreeRTOS}
