configName: keystream_connect
folderName: keystream_connect
format_version: v1.0
frameworkPath: C:\Users\sravicha\Harmony_Final_Validate
processor: ATSAMD21E18A
projectName: keystream_connect
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMD21_DFP\3.6.144
